### ISSUE TITLE
可视化时报错

### ISSUE THREAD

**Issue by sunjian2015** [PaddlePaddle/VisualDL#1066]
```
[ERROR 2022-04-20 11:11:37,329 lib.py:537] Unexpected error: <class 'AttributeError'>
'LogReader' object has no attribute 'data_manager'
<traceback object at 0x7fc149675388>
[ERROR 2022-04-20 11:11:39,331 lib.py:537] Unexpected error: <class 'AttributeError'>
'LogReader' object has no attribute 'data_manager'
<traceback object at 0x7fc149675708>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/visualdl/server/lib.py", line 533, in retry
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/visualdl/server/lib.py", line 69, in get_logs
    all_tag = log_reader.data_manager.get_reservoir(component).keys
AttributeError: 'LogReader' object has no attribute 'data_manager'
```
请问这个问题怎么解决，用的2.2.2

**Comment by rainyfly** [comment]
你是怎么使用的呢，有没有使用--logdir指定目录路径呢

**Comment by sunjian2015** [comment]
> 你是怎么使用的呢，有没有使用--logdir指定目录路径呢

指定了的，可能是版本的问题，后来我应该是更新了paddle也没改啥就没问题了...
