### ISSUE TITLE
看模型出现错误TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by hitbuyi** [PaddlePaddle/VisualDL#1137]
1，运行环境： 
conda: 4.13.0
paddlepaddle:  1.0.0
visual 2.4.1

2，运行下面的模型时
visualdl --model deploy/inference.pdmodel

出现了如下错误： 
(pddl) hitbuyi@hitbuyi-Dell-G15-5511:~/PycharmProjects/padlepadle|_project/SMOKE$ visualdl --model deploy/inference.pdmodel
VisualDL 2.4.1
Traceback (most recent call last):
  File "/home/hitbuyi/.conda/envs/pddl/bin/visualdl", line 8, in <module>
    sys.exit(main())
  File "/home/hitbuyi/.conda/envs/pddl/lib/python3.7/site-packages/visualdl/server/app.py", line 198, in main
    _run(args)
  File "/home/hitbuyi/.conda/envs/pddl/lib/python3.7/site-packages/visualdl/server/app.py", line 179, in _run
    app = create_app(args)
  File "/home/hitbuyi/.conda/envs/pddl/lib/python3.7/site-packages/visualdl/server/app.py", line 70, in create_app
    profiler_api_call = create_profiler_api_call(args.logdir)
  File "/home/hitbuyi/.conda/envs/pddl/lib/python3.7/site-packages/visualdl/component/profiler/profiler_server.py", line 302, in create_profiler_api_call
    api = ProfilerApi(logdir)
  File "/home/hitbuyi/.conda/envs/pddl/lib/python3.7/site-packages/visualdl/component/profiler/profiler_server.py", line 24, in __init__
    self._reader = ProfilerReader(logdir)
  File "/home/hitbuyi/.conda/envs/pddl/lib/python3.7/site-packages/visualdl/component/profiler/profiler_reader.py", line 69, in __init__
    self.runs()
  File "/home/hitbuyi/.conda/envs/pddl/lib/python3.7/site-packages/visualdl/component/profiler/profiler_reader.py", line 114, in runs
    self.profile_runs(update=update)
  File "/home/hitbuyi/.conda/envs/pddl/lib/python3.7/site-packages/visualdl/component/profiler/profiler_reader.py", line 100, in profile_runs
    flush_walks = self.get_all_walk()
  File "/home/hitbuyi/.conda/envs/pddl/lib/python3.7/site-packages/visualdl/component/profiler/profiler_reader.py", line 78, in get_all_walk
    for dir in self.dir:
TypeError: 'NoneType' object is not iterable

不知道是什么原因

**Comment by rainyfly** [comment]
你好，尝试指定一下logdir 参数

**Comment by Intsigstephon** [comment]
> eType' object is not ite

遇到同样的问题，macbook Pro M1 2020.  python3.8
