### ISSUE TITLE
词向量映射到低维空间 报错  

### ISSUE THREAD

**Issue by leigao-dev** [PaddlePaddle/VisualDL#1141]
# 获取词表中前1000个单词
labels = token_embedding.vocab.to_tokens(list(range(0, 1000)))
# 取出这1000个单词对应的Embedding
test_token_embedding = token_embedding.search(labels)

# 引入VisualDL的LogWriter记录日志
from visualdl import LogWriter

with LogWriter(logdir='./token_hidi') as writer:
    writer.add_embeddings(tag='test', mat=[i for i in test_token_embedding], metadata=labels)

根据日志文件进行可视化展示报错：
      TypeError: n.map is not a function
    at useComponents.js:1:896
    at Object.Zu [as useMemo] (index-6f69db2e.js:5:57563)
    at t.useMemo (index-655cebff.js:5:6676)
    at O (useComponents.js:1:857)
    at se (Navbar.js:104:1067)
    at di (index-6f69db2e.js:5:52892)
    at gi (index-6f69db2e.js:5:62334)
    at Ms (index-6f69db2e.js:9:9564)
    at Ps (index-6f69db2e.js:9:934)
    at vf (index-6f69db2e.js:9:865)

**Comment by rainyfly** [comment]
你好，这边复现没有出现问题，不知道你的visualdl的版本以及浏览器分别是什么。
这边复现时候用的
visualdl版本：2.4.1  
浏览器： Chrome

**Comment by leigao-dev** [comment]
NLP 打卡营 Ai Studio s上面报错的，现在按照教程进行，没办法进行词向量的复现

**Comment by rainyfly** [comment]
可以试试在aistudio的notebook里!pip install --upgrade visualdl升级一下版本， 并且使用chrome浏览器看看。
