### ISSUE TITLE
Mac os（Apple M1  16GB) 下visualdl 看log报错

### ISSUE THREAD

**Issue by Intsigstephon** [PaddlePaddle/VisualDL#1168]
VisualDL 2.3.0
Python(75451,0x100597d40) malloc: can't allocate region
:*** mach_vm_map(size=7809634753807712256, flags: 100) failed (error code=3)
Python(75451,0x100597d40) malloc: *** set a breakpoint in malloc_error_break to debug
Traceback (most recent call last):
  File "/Users/lubin10/Library/Python/3.8/bin/visualdl", line 8, in <module>
    sys.exit(main())
  File "/Users/lubin10/Library/Python/3.8/lib/python/site-packages/visualdl/server/app.py", line 191, in main
    _run(args)
  File "/Users/lubin10/Library/Python/3.8/lib/python/site-packages/visualdl/server/app.py", line 172, in _run
    app = create_app(args)
  File "/Users/lubin10/Library/Python/3.8/lib/python/site-packages/visualdl/server/app.py", line 68, in create_app
    api_call = create_api_call(args.logdir, args.model, args.cache_timeout)
  File "/Users/lubin10/Library/Python/3.8/lib/python/site-packages/visualdl/server/api.py", line 375, in create_api_call
    api = Api(logdir, model, cache_timeout)
  File "/Users/lubin10/Library/Python/3.8/lib/python/site-packages/visualdl/server/api.py", line 72, in __init__
    self._reader = LogReader(logdir)
  File "/Users/lubin10/Library/Python/3.8/lib/python/site-packages/visualdl/reader/reader.py", line 89, in __init__
    self.load_new_data(update=True)
  File "/Users/lubin10/Library/Python/3.8/lib/python/site-packages/visualdl/reader/reader.py", line 354, in load_new_data
    self.add_remain()
  File "/Users/lubin10/Library/Python/3.8/lib/python/site-packages/visualdl/reader/reader.py", line 294, in add_remain
    remain = self.reader.get_remain()
  File "/Users/lubin10/Library/Python/3.8/lib/python/site-packages/visualdl/reader/record_reader.py", line 106, in get_remain
    for item in self._reader:
  File "/Users/lubin10/Library/Python/3.8/lib/python/site-packages/visualdl/reader/record_reader.py", line 60, in __next__
    self._reader.get_next()
  File "/Users/lubin10/Library/Python/3.8/lib/python/site-packages/visualdl/reader/record_reader.py", line 40, in get_next
    event_str = self.file_handle.read(header_len)
  File "/Users/lubin10/Library/Python/3.8/lib/python/site-packages/visualdl/io/bfile.py", line 592, in read
    self.buff, self.continuation_token = self.fs.read(
  File "/Users/lubin10/Library/Python/3.8/lib/python/site-packages/visualdl/io/bfile.py", line 121, in read
    data = fp.read(size)
MemoryError

**Comment by Intsigstephon** [comment]
shell命令： visualdl --logdir ./logs

**Comment by rainyfly** [comment]
你好，这是由于日志的内容由于位置原因损坏，导致有一个记录内容长度的字段无效了，那个记录内容长度的字段由于无效了，vdl按照那个字段指示的长度去读内容，然后调用io的read方法去读那么多长度的字节，导致malloc失败
