### ISSUE TITLE
visualdl词向量演示实验报错

### ISSUE THREAD

**Issue by yepengxj** [PaddlePaddle/VisualDL#1191]
BML Codelab中进行词向量演示实验

```
# 获取词表中前1000个单词
labels = token_embedding.vocab.to_tokens(list(range(0, 1000)))
# 取出这1000个单词对应的Embedding
test_token_embedding = token_embedding.search(labels)

# 引入VisualDL的LogWriter记录日志
from visualdl import LogWriter

with LogWriter(logdir='./token_hidi') as writer:
    writer.add_embeddings(tag='test', mat=[i for i in test_token_embedding], metadata=labels)
```
更新visualdl至最新
`!pip install --upgrade visualdl`

在chrome、edge中操作均提示如下错误：
```
Uncaught (in promise) Error: Number of tensors (1000) do not match the number of lines in metadata (3841).
    at y (parser.js:2:1726)
    at parseFromBlob (parser.js:2:2627)
    at async parse-data.js:1:233
```

**Comment by rainyfly** [comment]
你好，可以试下如果在本地会不会出现这个错误。

**Comment by yepengxj** [comment]
在本地使用正常。
