### ISSUE TITLE
vdl可以打开 却无法读取里面的数据是为什么

### ISSUE THREAD

**Issue by qqwantu** [PaddlePaddle/VisualDL#1231]
Traceback (most recent call last):
  File "H:/PaddleSlim/vdl.py", line 5, in <module>
    data = reader.get_data('scalar', 'train/loss')
  File "E:\anaconda\envs\paddle\lib\site-packages\visualdl\reader\reader.py", line 112, in get_data
    return self._log_data[component][tag]
AttributeError: 'LogReader' object has no attribute '_log_data'

**Comment by rainyfly** [comment]
你好，可以贴一下你的python code么，LogReader里的文件接口有两组，一组是负责读logdir整个目录的，一组是负责读单个file的，即LogReader里指定file_path读单个文件。你这个接口貌似是读单个文件的？

**Comment by qqwantu** [comment]
![image](https://user-images.githubusercontent.com/68869183/224254045-c98bb5d4-b3fc-4484-a8c7-85263f8481d8.png)
![image](https://user-images.githubusercontent.com/68869183/224254072-7acc03ea-2168-440f-ac18-46836d947c72.png)
我直接复制示例的

**Comment by qqwantu** [comment]
![image](https://user-images.githubusercontent.com/68869183/224254260-53c946a5-f071-4a89-8e39-9ab976282552.png)

**Comment by rainyfly** [comment]
你的VDL版本是哪个呀，要不升级一下VDL试试。

**Comment by andyz168** [comment]
我也遇到这个问题

**Comment by rainyfly** [comment]
> 我也遇到这个问题

哪个版本的VDL
