### ISSUE TITLE
 verbose=True  KeyError: ''

### ISSUE THREAD

**Issue by ZYNORl** [PaddlePaddle/VisualDL#1238]
安装的是CPU版的paddle，` conda install paddlepaddle==2.4.2 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/`

我按照官方的[Graph Demo](https://github.com/PaddlePaddle/VisualDL/blob/develop/docs/components/README.md#graph--%E7%BD%91%E7%BB%9C%E7%BB%93%E6%9E%84%E7%BB%84%E4%BB%B6)来尝试使用Graph component，报错如下：
```
(vis_env) F:\result\test>python test_model.py
Failed to save model graph, error: ''
Traceback (most recent call last):
  File "test_model.py", line 40, in <module>
    verbose=True)
  File "D:\Miniconda\miniconda3\envs\vis_env\lib\site-packages\visualdl\writer\writer.py", line 668, in add_graph
    raise e
  File "D:\Miniconda\miniconda3\envs\vis_env\lib\site-packages\visualdl\writer\writer.py", line 665, in add_graph
    result = translate_graph(model, input_spec, verbose)
  File "D:\Miniconda\miniconda3\envs\vis_env\lib\site-packages\visualdl\component\graph\exporter.py", line 32, in translate_graph
    result = analyse_model(model_data)
  File "D:\Miniconda\miniconda3\envs\vis_env\lib\site-packages\visualdl\component\graph\graph_component.py", line 340, in analyse_model
    construct_edges(var_name, all_ops, all_vars, all_edges)
  File "D:\Miniconda\miniconda3\envs\vis_env\lib\site-packages\visualdl\component\graph\graph_component.py", line 158, in construct_edges
    _construct_edge(from_node, to_node)
  File "D:\Miniconda\miniconda3\envs\vis_env\lib\site-packages\visualdl\component\graph\graph_component.py", line 113, in _construct_edge
    parent_node = all_ops[src_base_node]['parent_node']
KeyError: ''
```

**Comment by ZYNORl** [comment]
已经解决了
logwrite接口应该过时了，换成了这个
```
#创建模型
model = MyNet()
#保存模型，获取模型结构文件
paddle.jit.save(model, './log/graph_test/MyNet', [paddle.static.InputSpec([-1,1,28,28])])
```

**Comment by rainyfly** [comment]
该问题产生的原因应该是代码没有考虑好跨平台下的兼容性问题，因为节点的层次路径表示用的是/，然后里面处理节点路径用的os.path的lib，在windows下是用\表示路径的，造成了bug。在下一个版本中进行修复。

**Comment by rainyfly** [comment]
修复的pr https://github.com/PaddlePaddle/VisualDL/pull/1244 。 这个修复将在下一个小版本中进入，如果需要在windows下使用，可以参考这个pr中修改的文件在本地对应修改一下。具体可以安装如下操作：
import visualdl
visualdl.__path__
看一下visualdl的安装路径，然后找到pr中修改的文件对应修改一下即能够生效。
