### ISSUE TITLE
在python3.10上无法启动visualdl

### ISSUE THREAD

**Issue by weixians** [PaddlePaddle/VisualDL#1242]
经过查验，主要是由于python3.10中的collections没有Mapping，而是转到了collections.abs包中

报错信息：
`Traceback (most recent call last):
    return _run_code(code, main_globals, None,
  File "D:\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Python\envs\sj_utiliity\Scripts\visualdl.exe\__main__.py", line 4, in <module>
  File "D:\Python\envs\sj_utiliity\lib\site-packages\visualdl\server\app.py", line 39, in <module>
  File "D:\Python\envs\sj_utiliity\lib\site-packages\visualdl\component\inference\fastdeploy_server.py", line 27, in <module>
    from .fastdeploy_client.client_app import create_gradio_client_app
  File "D:\Python\envs\sj_utiliity\lib\site-packages\visualdl\component\inference\fastdeploy_client\client_app.py", line 18, in <module>
    from .http_client_manager import get_metric_data
  File "D:\Python\envs\sj_utiliity\lib\site-packages\visualdl\component\inference\fastdeploy_client\http_client_manager.py", line 21, in <module>
  File "D:\Python\envs\sj_utiliity\lib\site-packages\attrdict\__init__.py", line 5, in <module>
    from attrdict.mapping import AttrMap
  File "D:\Python\envs\sj_utiliity\lib\site-packages\attrdict\mapping.py", line 4, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (D:\Python\Python310\lib\collections\__init__.py)
`

请尽快使用修改后的attrdict包

**Comment by rainyfly** [comment]
感谢，已经收到反馈

**Comment by weixians** [comment]
希望尽快修复

**Comment by rainyfly** [comment]
已经更新了
