### ISSUE TITLE
使用pip安装visualdl错误

### ISSUE THREAD

**Issue by litongjava** [PaddlePaddle/VisualDL#1246]
执行命令
python -m pip install visualdl -i https://mirror.baidu.com/pypi/simple
python version 3.8
server version ubuntu 20.0.4
error log
```
  Preparing metadata (setup.py) ... done
  Downloading https://mirror.baidu.com/pypi/packages/73/1b/513d05b856c32565fea7cd02c10c9deb09aee4d4969ca57e3e86ae12055e/gevent-0.13.8.tar.gz (300 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 300.1/300.1 kB 4.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-x49qd_sd/gevent_8d88b2380d4649aaa64e3af26e513efb/setup.py", line 95
          print 'Linking %s to %s' % (path_to_build_core_so, path_to_core_so)
                                 ^
      SyntaxError: invalid syntax
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
[root@ping-Inspiron-3458 ~]# 
```

**Comment by rainyfly** [comment]
用conda重新创建一个环境安装试试

**Comment by rainyfly** [comment]
已修复。
