### ISSUE TITLE
[Note] 关于在macos下使用visualdl

### ISSUE THREAD

**Issue by rainyfly** [PaddlePaddle/VisualDL#1251]
1. 由于VisualDL 2.5.0以上依赖了x2paddle来实现模型转换的能力，目前x2paddle并不支持macos，macos下的用户请使用2.4.2版本之前的visualdl。
```bash
pip install visualdl == 2.4.2
```

**Comment by Ethan-1996** [comment]
`error /Users/name/Downloads/VisualDL-2.5.0/frontend/node_modules/wasm-pack: Command failed.
Exit code: 1
Command: node ./install.js
Arguments: 
Directory: /Users/name/Downloads/VisualDL-2.5.0/frontend/node_modules/wasm-pack
Output:
/Users/name/Downloads/VisualDL-2.5.0/frontend/node_modules/wasm-pack/binary.js:19
  throw new Error(`Unsupported platform: ${type} ${arch}`);
  ^

Error: Unsupported platform: Darwin arm64
    at getPlatform (/Users/name/Downloads/VisualDL-2.5.0/frontend/node_modules/wasm-pack/binary.js:19:9)
    at getBinary (/Users/name/Downloads/VisualDL-2.5.0/frontend/node_modules/wasm-pack/binary.js:23:20)
    at install (/Users/name/Downloads/VisualDL-2.5.0/frontend/node_modules/wasm-pack/binary.js:37:18)
    at Object.<anonymous> (/Users/name/Downloads/VisualDL-2.5.0/frontend/node_modules/wasm-pack/install.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
`
如果你们和我遇到了一样的错误 请找到 ~根目录/frontend/packages/wasm/package.json 把wasm-pack更新到最新版本
我下载下来的是0.9.1 换成0.11.1后可以运行

**Comment by rainyfly** [comment]
该问题已经在visualdl 2.5.3版本中修复。
