### ISSUE TITLE
离线环境下使用

### ISSUE THREAD

**Issue by ArthurSec** [PaddlePaddle/VisualDL#1252]
无法访问互联网如何使用 visualdl ?
启动时抛出错误

VisualDL 2.5.2
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/visualdl/component/inference/model_convert_server.py", line 50, in __init__
    self.bos_client = BosFileSystem()
  File "/usr/local/lib/python3.8/dist-packages/visualdl/io/bfile.py", line 282, in __init__
    self.get_bos_config()
  File "/usr/local/lib/python3.8/dist-packages/visualdl/io/bfile.py", line 291, in get_bos_config
    raise KeyError('${BOS_HOST} is not found.')
KeyError: '${BOS_HOST} is not found.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 200, in _new_conn
    sock = connection.create_connection(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 604, in connect
    self.sock = sock = self._new_conn()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 207, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7fb133719580>: Failed to resolve 'www.paddlepaddle.org.cn' ([Errno -3] Temporary failure in name resolution)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.paddlepaddle.org.cn', port=443): Max retries exceeded with url: /paddle/visualdl/service/server/sts/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fb133719580>: Failed to resolve 'www.paddlepaddle.org.cn' ([Errno -3] Temporary failure in name resolution)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/visualdl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/visualdl/server/app.py", line 656, in main
    _run(args)
  File "/usr/local/lib/python3.8/dist-packages/visualdl/server/app.py", line 637, in _run
    app = create_app(args)
  File "/usr/local/lib/python3.8/dist-packages/visualdl/server/app.py", line 89, in create_app
    inference_api_call = create_model_convert_api_call()
  File "/usr/local/lib/python3.8/dist-packages/visualdl/component/inference/model_convert_server.py", line 263, in create_model_convert_api_call
    api = ModelConvertApi()
  File "/usr/local/lib/python3.8/dist-packages/visualdl/component/inference/model_convert_server.py", line 56, in __init__
    self.bos_client.renew_bos_client_from_server()
  File "/usr/local/lib/python3.8/dist-packages/visualdl/io/bfile.py", line 327, in renew_bos_client_from_server
    res = requests.post(url=url).json()
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.paddlepaddle.org.cn', port=443): Max retries exceeded with url: /paddle/visualdl/service/server/sts/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fb133719580>: Failed to resolve 'www.paddlepaddle.org.cn' ([Errno -3] Temporary failure in name resolution)"))

**Comment by rainyfly** [comment]
已修复。

**Comment by Halacky** [comment]
I have same problem. Do u have any solution for this issue?
