### ISSUE TITLE
在ai studio多卡多进程报错

### ISSUE THREAD

**Issue by tangpanyu** [PaddlePaddle/VisualDL#1253]
`writer = LogWriter(args.log_dir)`
Traceback (most recent call last):
  File "train.py", line 55, in <module>
    writer = LogWriter(args.log_dir)
  File "/usr/local/lib/python3.7/dist-packages/visualdl/writer/writer.py", line 119, in __init__
    self._get_file_writer()
  File "/usr/local/lib/python3.7/dist-packages/visualdl/writer/writer.py", line 139, in _get_file_writer
    filename=self._file_name)
  File "/usr/local/lib/python3.7/dist-packages/visualdl/writer/record_writer.py", line 90, in __init__
    bfile.makedirs(logdir)
  File "/usr/local/lib/python3.7/dist-packages/visualdl/io/bfile.py", line 695, in makedirs
    return default_file_factory.get_filesystem(path).makedirs(path)
  File "/usr/local/lib/python3.7/dist-packages/visualdl/io/bfile.py", line 97, in makedirs
    os.makedirs(path)
  File "/usr/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/root/paddlejob/workspace/output/_log'

**Comment by rainyfly** [comment]
这个是哪个版本的visualdl啊

**Comment by tangpanyu** [comment]
> 这个是哪个版本的visualdl啊

visualdl                2.4.1

**Comment by rainyfly** [comment]
更新一下版本试试
