### ISSUE TITLE
visualdl启动后，打开页面报错

### ISSUE THREAD

**Issue by bltcn** [PaddlePaddle/VisualDL#1261]
环境：docker paddlepaddle/fastdeploy:1.0.7-gpu-cuda11.6-trt8.5-22.12
VisualDL 2.5.3

下面是错误日志
root@localhost:/FastDeploy/examples# visualdl --host 0.0.0.0 --port 8080
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.0.2) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
VisualDL 2.5.3
Running VisualDL at http://0.0.0.0:8080/ (Press CTRL+C to quit)
[ERROR 2023-08-20 02:55:12,738 lib.py:637] Unexpected error: <class 'AttributeError'>
'LogReader' object has no attribute '_model'
<traceback object at 0x7fd9ca415340>
[ERROR 2023-08-20 02:55:14,740 lib.py:637] Unexpected error: <class 'AttributeError'>
'LogReader' object has no attribute '_model'
<traceback object at 0x7fd9ca4150c0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/visualdl/server/lib.py", line 633, in retry
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/visualdl/server/lib.py", line 585, in get_static_graph
    if log_reader.model:
  File "/usr/local/lib/python3.8/dist-packages/visualdl/reader/reader.py", line 100, in model
    return self._model
AttributeError: 'LogReader' object has no attribute '_model'
[ERROR 2023-08-20 02:55:16,743 api.py:75] Internal server error. Retry later.
界面也不正常
![image](https://github.com/PaddlePaddle/VisualDL/assets/7421901/03da8b7a-263d-4e17-a305-f611d344ef3b)
只有一个导航项

**Comment by zgsxwsdxg** [comment]
我也遇到了同样的问题，你解决了么？谢谢

**Comment by AILaborer** [comment]
切换到 2.5.2版本后可以打开

**Comment by iioiioio** [comment]
启动命令增加参数

visualdl --logdir ./log --host 0.0.0.0 --port 8080 --component_tabs scalar image text embeddings audio histogram hyper_parameters static_graph dynamic_graph pr_curve roc_curve profiler x2paddle fastdeploy_server fastdeploy_client

然后升级一下requests

**Comment by suorui7** [comment]
> 我也遇到了同样的问题，你解决了么？谢谢
我想问一下，解决了吗？我也遇到了，2.5.2依旧存在这个问题。

**Comment by iioiioio** [comment]
> > 我也遇到了同样的问题，你解决了么？谢谢
> > 我想问一下，解决了吗？我也遇到了，2.5.2依旧存在这个问题。

升级一下requests，启动是使用参数 --component_tabs   增加组件（https://github.com/PaddlePaddle/VisualDL#launch-by-command-line），启动命令如：visualdl --logdir ./log --host 0.0.0.0 --port 8080 --component_tabs scalar image text embeddings audio histogram hyper_parameters static_graph dynamic_graph pr_curve roc_curve profiler x2paddle fastdeploy_server fastdeploy_client
