### ISSUE TITLE
visualDL --logdir ./random_log --port 8080 error

### ISSUE THREAD

**Issue by realsnake** [PaddlePaddle/VisualDL#322]
Traceback (most recent call last):
  File "/usr/local/bin/visualDL", line 14, in <module>
    import visualdl.server.graph as vdl_graph
  File "/usr/local/lib/python2.7/dist-packages/visualdl/server/graph.py", line 9, in <module>
    from . import onnx
  File "/usr/local/lib/python2.7/dist-packages/visualdl/server/onnx/__init__.py", line 8, in <module>
    from .onnx_pb2 import ModelProto
  File "/usr/local/lib/python2.7/dist-packages/visualdl/server/onnx/onnx_pb2.py", line 213, in <module>
    options=None, file=DESCRIPTOR),
TypeError: __init__() got an unexpected keyword argument 'file'

**Comment by jetfuel** [comment]
@realsnake Sorry for the delay. It seems that the Protobuf package is not up to date. You should be able to fix the issue with `pip install --upgrade protobuf` or `pip install --upgrade visualdl` 
Thank your for using the tool

**Comment by realsnake** [comment]
Thanks， it works.
