### ISSUE TITLE
IOError: [Errno 2] No such file or directory: './testing.wav'

### ISSUE THREAD

**Issue by daming-lu** [PaddlePaddle/VisualDL#379]
![screen shot 2018-04-09 at 5 59 28 pm](https://user-images.githubusercontent.com/5635322/38530515-d41552ec-3c1f-11e8-9d8c-26343f8ecd99.png)

**Comment by daming-lu** [comment]
And when I put a valid .wav file, there is another error like below:

```
(venv) DamingLu:VisualDL ludaming$ [develop]$ vdl_create_scratch_log
Traceback (most recent call last):
  File "/Users/ludaming/Baidu_USA_DamingLu/visualdl/VisualDL/venv/bin/vdl_create_scratch_log", line 101, in <module>
    f = wave.open('./testing.wav', "rb")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wave.py", line 511, in open
    return Wave_read(f)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wave.py", line 164, in __init__
    self.initfp(f)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wave.py", line 144, in initfp
    self._read_fmt_chunk(chunk)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wave.py", line 274, in _read_fmt_chunk
    raise Error, 'unknown format: %r' % (wFormatTag,)
wave.Error: unknown format: 3
```

**Comment by daming-lu** [comment]
https://github.com/PaddlePaddle/VisualDL/pull/382
