### ISSUE TITLE
WARNING: Do not use the development server in a production environment.

### ISSUE THREAD

**Issue by J-Zhujj** [PaddlePaddle/VisualDL#446]
WARNING: Do not use the development server in a production environment.
Launch DL，throw exception，What should I do?

**Comment by daming-lu** [comment]
@J-Zhujj : thanks for your interest in VisualDL. Can you paste the exception or a screenshot? That can help us find the issue better. Thank you 😁

**Comment by Haninini** [comment]
i also got same warning.
 Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/usr/local/lib/python3.4/dist-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/flask/cli.py", line 767, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/usr/local/lib/python3.4/dist-packages/flask/cli.py", line 293, in __init__
    self._load_unlocked()
  File "/usr/local/lib/python3.4/dist-packages/flask/cli.py", line 317, in _load_unlocked
    self._app = rv = self.loader()
  File "/usr/local/lib/python3.4/dist-packages/flask/cli.py", line 372, in load_app
    app = locate_app(self, import_name, name)
  File "/usr/local/lib/python3.4/dist-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/home/hana/Flasks_apps/sample.py", line 3
    @app.route(‘/sample’)
               ^
SyntaxError: invalid character in identifier

**Comment by codes67** [comment]
```
C:\Users\yogesh\Desktop\python programming> python website1.py
 * Serving Flask app "website1" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 672-977-358
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [14/Jun/2018 05:55:44] "GET / HTTP/1.1" 200 `-```

I got this warning error ..!! Does it have any significance or not? Thank you
```

**Comment by kushmilan** [comment]
Same warning.

flask run
 * Serving Flask app "application.py"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "c:\users\milan\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\milan\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Milan\AppData\Local\Programs\Python\Python36-32\Scripts\flask.exe\__main__.py", line 9, in <module>
  File "c:\users\milan\appdata\local\programs\python\python36-32\lib\site-packages\flask\cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "c:\users\milan\appdata\local\programs\python\python36-32\lib\site-packages\flask\cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "c:\users\milan\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\milan\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\milan\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\milan\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\milan\appdata\local\programs\python\python36-32\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "c:\users\milan\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\milan\appdata\local\programs\python\python36-32\lib\site-packages\flask\cli.py", line 767, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "c:\users\milan\appdata\local\programs\python\python36-32\lib\site-packages\flask\cli.py", line 293, in __init__
    self._load_unlocked()
  File "c:\users\milan\appdata\local\programs\python\python36-32\lib\site-packages\flask\cli.py", line 317, in _load_unlocked
    self._app = rv = self.loader()
  File "c:\users\milan\appdata\local\programs\python\python36-32\lib\site-packages\flask\cli.py", line 372, in load_app
    app = locate_app(self, import_name, name)
  File "c:\users\milan\appdata\local\programs\python\python36-32\lib\site-packages\flask\cli.py", line 235, in locate_app
    __import__(module_name)
  File "C:\test\application.py", line 1
    import flask from Flask
                    ^
SyntaxError: invalid syntax

**Comment by NKVDL** [comment]
Same

(CodexA) 192:~ NVDL$ flask run
 * Serving Flask app "kerasvis.runserver"
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "kerasvis.runserver", an ImportError was raised:

Traceback (most recent call last):
  File "/anaconda3/envs/CodexA/lib/python3.6/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/anaconda3/envs/CodexA/lib/python3.6/site-packages/kerasvis/runserver.py", line 1, in <module>
    from kerasvis.server.main import app
  File "/anaconda3/envs/CodexA/lib/python3.6/site-packages/kerasvis/server/main.py", line 4, in <module>
    from .plots import empty_plot, loss_accuracy_plot
  File "/anaconda3/envs/CodexA/lib/python3.6/site-packages/kerasvis/server/plots.py", line 3, in <module>
    from bokeh.charts import Line
ModuleNotFoundError: No module named 'bokeh.charts'

(CodexA) 192:~ NVDL$ pip install flask
Requirement already satisfied: flask in /anaconda3/envs/CodexA/lib/python3.6/site-packages (1.0.2)
Requirement already satisfied: Werkzeug>=0.14 in /anaconda3/envs/CodexA/lib/python3.6/site-packages (from flask) (0.14.1)
Requirement already satisfied: itsdangerous>=0.24 in /anaconda3/envs/CodexA/lib/python3.6/site-packages (from flask) (0.24)
Requirement already satisfied: Jinja2>=2.10 in /anaconda3/envs/CodexA/lib/python3.6/site-packages (from flask) (2.10)
Requirement already satisfied: click>=5.1 in /anaconda3/envs/CodexA/lib/python3.6/site-packages (from flask) (6.7)
Requirement already satisfied: MarkupSafe>=0.23 in /anaconda3/envs/CodexA/lib/python3.6/site-packages (from Jinja2>=2.10->flask) (1.0)
(CodexA) 192:~ NVDL$

**Comment by bschley** [comment]
Try to start the server with the development env.

```
$ export FLASK_APP=yourapp
$ export FLASK_ENV=development
```

and then you start the server with:

`$ flask run`

**Comment by Rhyanz46** [comment]
in flask configuration class add : 
`ENV = ""`

like : 
`DEBUG = True`

**Comment by eliyahusternberg** [comment]
I am getting the same error not sure whats going on

**Comment by bschley** [comment]
`WARNING: Do not use the development server in a production environment.`

Is only a warning. Then means, if you run your site in the world wide web... then don't activate the developement mode on THAT specific server, for security reasons.

And if you added the environment variables make sure you add them as a user or global enviroment varialble... depends of the user you use.

**Comment by eliyahusternberg** [comment]
I get this error while trying to run the application from Miguel Grinberg

**Comment by eliyahusternberg** [comment]
flask.cli.NoAppException: Could not import "microblog".

Traceback (most recent call last)
File "/Users/eliyahusternberg/Desktop/sign_in/venv/lib/python3.6/site-packages/flask/cli.py", line 330, in __call__
rv = self._load_unlocked()
File "/Users/eliyahusternberg/Desktop/sign_in/venv/lib/python3.6/site-packages/flask/cli.py", line 317, in _load_unlocked
self._app = rv = self.loader()
File "/Users/eliyahusternberg/Desktop/sign_in/venv/lib/python3.6/site-packages/flask/cli.py", line 372, in load_app
app = locate_app(self, import_name, name)
File "/Users/eliyahusternberg/Desktop/sign_in/venv/lib/python3.6/site-packages/flask/cli.py", line 246, in locate_app
'Could not import "{name}".'.format(name=module_name)
flask.cli.NoAppException: Could not import "microblog".

**Comment by eliyahusternberg** [comment]
Thanks however I still get an import error when I go to
http://localhost:5000/index.

**Comment by meenusheok** [comment]
In case of window use set at the place of export:-
set FLASK_ENV=development
flask run
and then run your python file

**Comment by eliyahusternberg** [comment]
Thanks

**Comment by qijunbo** [comment]
env FLASK_ENV=development FLASK_APP=hello.py flask run

**Comment by enea1982** [comment]
hello you can give me a hand on a telegram bot

**Comment by enea1982** [comment]
when I start the bot app.py
this screen comes to me
pi@admin:~/fastcoinbot $ python3 app.py
2018-10-21 17:40:27,505 - super-bot - INFO - Starting bot
2018-10-21 17:40:27,505 - super-bot - INFO - Load config
2018-10-21 17:40:27,507 - super-bot - INFO - Connect to Telegram
2018-10-21 17:40:27,510 - super-bot - INFO - Collect modules
2018-10-21 17:40:27,938 - super-bot - INFO - Ready
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
2018-10-21 17:40:27,992 - werkzeug - INFO -  * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)

**Comment by raymanbigD** [comment]
I had the same issue . I solved it by just running the ip address as an argument within flask

app.run('localhost', 5000)

**Comment by prigioni** [comment]
> I had the same issue . I solved it by just running the ip address as an argument within flask
> 
> app.run('localhost', 5000)

it well done

**Comment by Lobsterrr** [comment]
> In case of window use set at the place of export:-
> set FLASK_ENV=development
> flask run
> and then run your python file

Thanks this really works.

**Comment by Sasi-007** [comment]
Issue::

F:\web\Python webapps>flask run
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.

**Comment by Sasi-007** [comment]
@Lobsterrr Can u explain me briefly step by step those steps bcz i have set path in environment variables but it doesn't work.

**Comment by yuanyuan999** [comment]
> 尝试使用开发环境启动服务器。
> 
> ```
> $ export FLASK_APP=yourapp
> $ export FLASK_ENV=development
> ```
> 
> 然后使用以下命令启动服务器：
> 
> `$ flask run`

牛逼牛逼兄弟

**Comment by Shafi-gethub** [comment]
How should i solve this Error, Im running it in windows 10 CMD
(env) C:\Users\Gilan\Desktop\ShafiFOLDER>set FLASK_New = D.py

(env) C:\Users\Gilan\Desktop\ShafiFOLDER>flask run
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

**Comment by PeterPanZH** [comment]
VisualDL is designed to visualize deep learning in a self-hosted environment. So we use flask as a web server to host frontend files. If you want to use visualdl as a server, please consider using a production WSGI server instead. You can refer to [Flask Document](https://flask.palletsprojects.com/en/1.1.x/deploying/uwsgi/) for more infomation.

**Comment by harshalDharpure** [comment]
> In case of window use set at the place of export:-
> set FLASK_ENV=development
> flask run
> and then run your python file

it works on windows

**Comment by jefinpaul** [comment]
If anyone is running this is anaconda, don't run this in power shell but in anaconda prompt

**Comment by kardotinambunan12** [comment]
im setting in .flaskenv   FLASK_APP=run.py
FLASK_ENV=development
FLASK_DEBUG=1



im to try "flask run" but error,  

* Serving Flask app "run.py" (lazy loading)
 * Environment: development
 * Debug mode: on
Traceback (most recent call last):
  File "/home/tog/Documents/python_flask/venv/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/tog/Documents/python_flask/venv/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/tog/Documents/python_flask/venv/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/tog/Documents/python_flask/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/tog/Documents/python_flask/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tog/Documents/python_flask/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tog/Documents/python_flask/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/tog/Documents/python_flask/venv/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/tog/Documents/python_flask/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/tog/Documents/python_flask/venv/lib/python3.8/site-packages/flask/cli.py", line 852, in run_command
    run_simple(
  File "/home/tog/Documents/python_flask/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 1030, in run_simple
    s.bind(server_address)
OSError: [Errno 98] Address already in use

**Comment by Jayanth1812** [comment]
With hello.py it is working "Hello word". 
But when I run the app (webhook_weather.py) it is not working, I am getting following error:

(helloworld-x2biACXm) C:\Users\Jayanth\Desktop\helloworld>python webhook_weather.py
Starting app on port 80
 * Serving Flask app 'webhook_weather' (lazy loading)
 * Environment: development
 * Debug mode: on
 * Restarting with stat
Starting app on port 80
 * Debugger is active!
 * Debugger PIN: 119-286-619
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://192.168.43.87:80/ (Press CTRL+C to quit)
192.168.43.87 - - [04/Jun/2021 14:38:39] "GET / HTTP/1.1" 404 -

Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by Pralay01** [comment]
command:
set FLASK_APP=abc.py(file name)
flask run

**Comment by Jayanth1812** [comment]
I am getting the AttributeError: when I run the python file
http://192.168.43.87:80/webhook

AttributeError: 'NoneType' object has no attribute 'get'

Traceback (most recent call last)
File "C:\Users\Jayanth.virtualenvs\helloworld-CPu4KsHf\lib\site-packages\flask\app.py", line 2088, in call
return self.wsgi_app(environ, start_response)
File "C:\Users\Jayanth.virtualenvs\helloworld-CPu4KsHf\lib\site-packages\flask\app.py", line 2073, in wsgi_app
response = self.handle_exception(e)
File "C:\Users\Jayanth.virtualenvs\helloworld-CPu4KsHf\lib\site-packages\flask\app.py", line 2070, in wsgi_app
response = self.full_dispatch_request()
File "C:\Users\Jayanth.virtualenvs\helloworld-CPu4KsHf\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\Users\Jayanth.virtualenvs\helloworld-CPu4KsHf\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
rv = self.dispatch_request()
File "C:\Users\Jayanth.virtualenvs\helloworld-CPu4KsHf\lib\site-packages\flask\app.py", line 1499, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "D:\ExcelSoft\venil\Cognitive-Behavioural-Chatbot-master\helloworld\web.py", line 26, in webhook
res = processRequest(req)
File "D:\ExcelSoft\venil\Cognitive-Behavioural-Chatbot-master\helloworld\web.py", line 36, in processRequest
print ("starting processRequest...",req.get("result").get("action"))
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by Jayanth1812** [comment]
AttributeError
AttributeError: 'NoneType' object has no attribute 'get'

Traceback (most recent call last)
File "C:\Users\Jayanth\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2464, in __call__
return self.wsgi_app(environ, start_response)
File "C:\Users\Jayanth\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2450, in wsgi_app
response = self.handle_exception(e)
File "C:\Users\Jayanth\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1867, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\Users\Jayanth\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 39, in reraise
raise value
File "C:\Users\Jayanth\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "C:\Users\Jayanth\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\Users\Jayanth\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\Users\Jayanth\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 39, in reraise
raise value
File "C:\Users\Jayanth\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "C:\Users\Jayanth\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "D:\ExcelSoft\venil\Cognitive-Behavioural-Chatbot-master\helloworld\web.py", line 26, in webhook
res = processRequest(req)
File "D:\ExcelSoft\venil\Cognitive-Behavioural-Chatbot-master\helloworld\web.py", line 36, in processRequest
print ("starting processRequest...",req.get("result").get("action"))
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by ghost** [comment]
> Issue::
> 
> F:\web\Python webapps>flask run
> 
> * Environment: production
>   WARNING: This is a development server. Do not use it in a production deployment.
>   Use a production WSGI server instead.
> * Debug mode: off
>   Usage: flask run [OPTIONS]
> 
> Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.

Hi! Sorry about question: how did you fixed this bug?

**Comment by StarlightScripter** [comment]
> I am getting the same error not sure whats going on

Hi, just change this part of code: `posts = requests.get("https://api.npoint.io/6e7d01d41a0536869eb9").json()` the url is old and not working. And if you don't want to get warning set env. variable as `FLASK_ENV=development`

**Comment by abolfazlrastgou** [comment]
Try gevent:
```

from flask import Flask
from gevent.pywsgi import WSGIServer

app = Flask(__name__)

@app.route('/api', methods=['GET'])
def index():
    return "Hello, World!"

if __name__ == '__main__':
    # Debug/Development
    # app.run(debug=True, host="0.0.0.0", port="5000")
    # Production
    http_server = WSGIServer(('', 5000), app)
    http_server.serve_forever()
```
Note: Install gevent using pip install gevent
