### ISSUE TITLE
Run VidualDL get Exception

### ISSUE THREAD

**Issue by seiriosPlus** [PaddlePaddle/VisualDL#462]
As the title says:
```
Traceback (most recent call last):
  File "/usr/local/bin/visualDL", line 29, in <module>
    import visualdl.server.graph as vdl_graph
  File "/usr/local/lib/python2.7/dist-packages/visualdl/server/graph.py", line 23, in <module>
    from . import onnx
  File "/usr/local/lib/python2.7/dist-packages/visualdl/server/onnx/__init__.py", line 8, in <module>
    from .onnx_pb2 import ModelProto
  File "/usr/local/lib/python2.7/dist-packages/visualdl/server/onnx/onnx_pb2.py", line 213, in <module>
    options=None, file=DESCRIPTOR),
TypeError: __new__() got an unexpected keyword argument 'file'
```

**Comment by seiriosPlus** [comment]
![image](https://user-images.githubusercontent.com/5442383/41694650-dc146ecc-753d-11e8-9222-21fb71d0a6d6.png)

The graph is confusing.

**Comment by oraoto** [comment]
I can reproduce this error by installing a older version of protobuf: `pip install protobuf==3.3
`.

@seiriosPlus  What's your protobuf verion?

**Comment by oraoto** [comment]
In https://github.com/PaddlePaddle/VisualDL/pull/286/commits/2559e2513f784fe40382e420a6536028e55508dc , protobuf was bump to 3.5, but we don't specify it in `setup.py`, this leads to the issue.
