### ISSUE TITLE
在ubuntu使用VisualDL报以下错误

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/VisualDL#474]
我使用pip和源码编译都试过了，还是报错，错误日志：
```
root@test:/home/test/VisualDL# visualdl --logdir ./scratch_log --port 8080
Traceback (most recent call last):
  File "/usr/local/bin/visualdl", line 29, in <module>
    import visualdl.server.graph as vdl_graph
  File "/usr/local/lib/python2.7/dist-packages/visualdl/server/graph.py", line 23, in <module>
    from . import onnx
  File "/usr/local/lib/python2.7/dist-packages/visualdl/server/onnx/__init__.py", line 8, in <module>
    from .onnx_pb2 import ModelProto
  File "/usr/local/lib/python2.7/dist-packages/visualdl/server/onnx/onnx_pb2.py", line 213, in <module>
    options=None, file=DESCRIPTOR),
TypeError: __init__() got an unexpected keyword argument 'file'
```

**Comment by oraoto** [comment]
protobuf版本问题，`pip list `看看你的protobuf版本是不是小于3.4。

试试在virtualenv里安装visualdl和protobuf==3.5。

**Comment by oraoto** [comment]
类似的问题: https://github.com/PaddlePaddle/VisualDL/issues/462

**Comment by yeyupiaoling** [comment]
@oraoto 的确，在安装paddlepaddle-gpu的时候需要的是3.1.0的，所以就错了。谢谢您的回答。
