### ISSUE TITLE
Exception on /data/runs

### ISSUE THREAD

**Issue by nbro** [PaddlePaddle/VisualDL#523]
### Problem

I am getting the following errors after having executed the command `visualDL --logdir ./log --port 7070` on the terminal and having gone to the URL `http://0.0.0.0:7070/`, under a Conda environment. This occurs before I run my PyTorch program.

```
[INFO 2019-01-05 16:45:51,774 visualDL:330]  port=7070
 * Serving Flask app "visualDL" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
[INFO 2019-01-05 16:45:51,975 _internal.py:88]  * Running on http://0.0.0.0:7070/ (Press CTRL+C to quit)
[INFO 2019-01-05 16:45:57,916 _internal.py:88] 127.0.0.1 - - [05/Jan/2019 16:45:57] "GET / HTTP/1.1" 302 -
[INFO 2019-01-05 16:45:57,920 _internal.py:88] 127.0.0.1 - - [05/Jan/2019 16:45:57] "GET /static/index.html HTTP/1.1" 200 -
[INFO 2019-01-05 16:45:57,963 _internal.py:88] 127.0.0.1 - - [05/Jan/2019 16:45:57] "GET /static/manifest.6eada1dada3243073429.js HTTP/1.1" 200 -
[INFO 2019-01-05 16:45:57,963 _internal.py:88] 127.0.0.1 - - [05/Jan/2019 16:45:57] "GET /static/index.6eada1dada3243073429.js HTTP/1.1" 200 -
[INFO 2019-01-05 16:45:57,966 _internal.py:88] 127.0.0.1 - - [05/Jan/2019 16:45:57] "GET /static/vendor.b20f919e100f2dfd568b.js HTTP/1.1" 200 -
[INFO 2019-01-05 16:45:58,569 _internal.py:88] 127.0.0.1 - - [05/Jan/2019 16:45:58] "GET /data/language HTTP/1.1" 200 -
[WARNING 2019-01-05 16:45:58,570 lib.py:388] update cache /data/runs
[ERROR 2019-01-05 16:45:58,570 app.py:1761] Exception on /data/runs [GET]
Traceback (most recent call last):
  File "/Users/nbro/anaconda3/envs/project/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nbro/anaconda3/envs/project/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nbro/anaconda3/envs/project/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/nbro/anaconda3/envs/project/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/nbro/anaconda3/envs/project/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nbro/anaconda3/envs/project/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nbro/anaconda3/envs/project/bin/visualDL", line 171, in runs
    data = cache_get('/data/runs', lib.get_modes, log_reader)
  File "/Users/nbro/anaconda3/envs/project/lib/python3.6/site-packages/visualdl/server/lib.py", line 389, in _handler
    data = func(*args, **kwargs)
  File "/Users/nbro/anaconda3/envs/project/lib/python3.6/site-packages/visualdl/server/lib.py", line 33, in get_modes
    return storage.modes()
  File "/Users/nbro/anaconda3/envs/project/lib/python3.6/site-packages/visualdl/python/storage.py", line 83, in modes
    return self.reader.modes()
RuntimeError: [/Users/nepepl/Desktop/VisualDL/visualdl/utils/filesystem.h:63] 
[INFO 2019-01-05 16:45:58,572 _internal.py:88] 127.0.0.1 - - [05/Jan/2019 16:45:58] "GET /data/runs HTTP/1.1" 500 -
[WARNING 2019-01-05 16:45:58,648 lib.py:388] update cache /data/plugin/scalars/tags
[ERROR 2019-01-05 16:45:58,648 lib.py:380] Unexpected error: <class 'RuntimeError'>
[/Users/nepepl/Desktop/VisualDL/visualdl/utils/filesystem.h:63] 
<traceback object at 0x11a9c0348>
[WARNING 2019-01-05 16:45:58,658 lib.py:388] update cache /data/plugin/histograms/tags
[ERROR 2019-01-05 16:45:58,659 lib.py:380] Unexpected error: <class 'RuntimeError'>
[/Users/nepepl/Desktop/VisualDL/visualdl/utils/filesystem.h:63] 
<traceback object at 0x11a176188>
[INFO 2019-01-05 16:45:58,771 _internal.py:88] 127.0.0.1 - - [05/Jan/2019 16:45:58] "GET /static/favicon.png HTTP/1.1" 404 -
[ERROR 2019-01-05 16:46:00,650 lib.py:380] Unexpected error: <class 'RuntimeError'>
[/Users/nepepl/Desktop/VisualDL/visualdl/utils/filesystem.h:63] 
<traceback object at 0x11a9b5e48>
[ERROR 2019-01-05 16:46:00,664 lib.py:380] Unexpected error: <class 'RuntimeError'>
[/Users/nepepl/Desktop/VisualDL/visualdl/utils/filesystem.h:63] 
<traceback object at 0x11a176248>
[ERROR 2019-01-05 16:46:02,656 lib.py:380] Unexpected error: <class 'RuntimeError'>
[/Users/nepepl/Desktop/VisualDL/visualdl/utils/filesystem.h:63] 
<traceback object at 0x11a9c0348>
[ERROR 2019-01-05 16:46:02,665 lib.py:380] Unexpected error: <class 'RuntimeError'>
[/Users/nepepl/Desktop/VisualDL/visualdl/utils/filesystem.h:63] 
<traceback object at 0x11a176188>
[ERROR 2019-01-05 16:46:04,658 visualDL:59] server temporary error, will retry latter.
[INFO 2019-01-05 16:46:04,659 _internal.py:88] 127.0.0.1 - - [05/Jan/2019 16:46:04] "GET /data/plugin/scalars/tags HTTP/1.1" 200 -
[ERROR 2019-01-05 16:46:04,667 visualDL:59] server temporary error, will retry latter.
[INFO 2019-01-05 16:46:04,668 _internal.py:88] 127.0.0.1 - - [05/Jan/2019 16:46:04] "GET /data/plugin/histograms/tags HTTP/1.1" 200 -
```

What I see when I go to the mentioned URL:

<img width="1426" alt="screen shot 2019-01-05 at 17 17 22" src="https://user-images.githubusercontent.com/9349000/50726478-dd815b00-110d-11e9-9d64-2addc8a947c0.png">

### Specifications

- Python 3.6.7 :: Anaconda, Inc.

**Comment by nbro** [comment]
I think the problem was due to the fact that I was not running the command `visualDL --logdir ./log --port 7070` from where the `log` folder is located (which, apparently, must exist before executing the command). I ran the command from the folder containing the `log` sub-folder, after having executed my PyTorch program, and now I'm not getting the error.

I think that VisualDL should not crash only because the log folder doesn't exist yet. I think this should be fixed.

**Comment by nbro** [comment]
I noticed that you can also have the error 

```
RuntimeError: [/Users/nepepl/Desktop/VisualDL/visualdl/utils/filesystem.h:63] 
```

but when you read the logging data from the file system using `LogReader` (see an example of how to do it [here](https://github.com/nbro/visualdl_with_pytorch_example/blob/master/read_visualdl_data.py)). You can have this error if e.g. in the statement `logger.scalar("scalars/train_loss")`, `"scalars/train_loss"` was not an "id" or "tag" with which you saved your logging data.

**Comment by nepeplwu** [comment]
Hi nbro, thank you for your feedback. We'll add more valid hints in future releases when VisualDL is started with an empty log dir

**Comment by nepeplwu** [comment]
Hi, nbro, thank you for your feedback. We'll add more valid hints in future releases when VisualDL is started with an empty log dir
