### ISSUE TITLE
How to use VisualDL in  python train（ Installation with virtualenv）

### ISSUE THREAD

**Issue by annualLXJ** [PaddlePaddle/VisualDL#541]
PROBLEM:
if I want use VisualDL , what should I write in my train file
ERROR:

(vdl) root@ubuntu16:/paddle/openCV/opencv-4.1.0/my_build_dir/Paddle/build/lac# visualdl --logdir=models --port=8080
[INFO 2019-04-25 11:01:42,991 visualdl:336]  port=8080
 * Serving Flask app "visualdl" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/VisualDL/VisualDL/vdl/bin/visualdl", line 338, in <module>
    app.run(debug=False, host=args.host, port=args.port, threaded=True)
  File "/VisualDL/VisualDL/vdl/lib/python3.5/site-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/VisualDL/VisualDL/vdl/lib/python3.5/site-packages/werkzeug/serving.py", line 990, in run_simple
    inner()
  File "/VisualDL/VisualDL/vdl/lib/python3.5/site-packages/werkzeug/serving.py", line 943, in inner
    fd=fd,
  File "/VisualDL/VisualDL/vdl/lib/python3.5/site-packages/werkzeug/serving.py", line 786, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/VisualDL/VisualDL/vdl/lib/python3.5/site-packages/werkzeug/serving.py", line 679, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

**Comment by oraoto** [comment]
> (vdl) root@ubuntu16:/paddle/openCV/opencv-4.1.0/my_build_dir/Paddle/build/lac# visualdl --logdir=models --port=8080
> ...
> OSError: [Errno 98] Address already in use

Some other application is using port 8080, you can specify other ports.
