### ISSUE TITLE
TypeError: stat: can't specify None for path argument

### ISSUE THREAD

**Issue by IMJerryChen** [PaddlePaddle/VisualDL#555]
[ERROR 2019-07-23 02:58:48,139 app.py:1891] Exception on /data/plugin/graphs/graph [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/bin/visualdl", line 323, in graph
    if model.is_onnx_model(args.model_pb):
  File "/usr/local/lib/python3.5/dist-packages/visualdl/server/model/onnx/__init__.py", line 13, in is_onnx_model
    if not os.path.isfile(model_path):
  File "/usr/lib/python3.5/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: can't specify None for path argument

**Comment by linshuliang** [comment]
protobuf 版本太高，会导致graph无法显示。
重装 protobuf，可以解决这个问题：
```
pip install protobuf==3.6.1
```

**Comment by IMJerryChen** [comment]
尝试降低protobuf版本  并没有效果呢

**Comment by linshuliang** [comment]
报错的原因，是不是没有指定路径？
在命令行执行 `visualdl` 命令时， 

* `--logdir`        : 指定 打点数据的路径；
* `--host`          : 指定主机名；
* `--port`          : 指定端口；
* `--model_pb` : 指定 model_graph 的路径；

例如：

```
visualdl --logdir ./log --host 0.0.0.0 --port 8080 --model_pb paddle_lenet_5_model
```

**Comment by IMJerryChen** [comment]
我运行的这个例子 
# 运行一个例子，vdl_create_scratch_log 将创建测试日志
vdl_create_scratch_log
visualdl --logdir=scratch_log --port=8080 

请问想看gragh的话 需要跟--model_pb吗

**Comment by linshuliang** [comment]
如果想查看 Graph 功能，都必须在 `visualdl` 命令中添加 `--model_pb` 选项来指定 graph_model 的路径。

例如：

```
vdl_create_scratch_log
visualdl --logdir=scratch_log --model_pb scratch_log/mnist_model.onnx
```

**Comment by IMJerryChen** [comment]
啊啊，已经解决，谢谢您~
