### ISSUE TITLE
训练时出现下面错误RuntimeError: [/work/VisualDL/visualdl/logic/sdk.cc:222] 

### ISSUE THREAD

**Issue by IMJerryChen** [PaddlePaddle/VisualDL#556]
Traceback (most recent call last):
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/root/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/opt/sign2class/train_densenet_vdl.py", line 306, in <module>
    main()
  File "/opt/sign2class/train_densenet_vdl.py", line 253, in main
    epoch_end_callback=[add_image_histogram()],)
  File "/usr/local/lib/python3.5/dist-packages/mxnet/model.py", line 907, in fit
    sym_gen=self.sym_gen)
  File "/usr/local/lib/python3.5/dist-packages/mxnet/model.py", line 366, in _train_multi_device
    _multiple_callbacks(epoch_end_callback, epoch, symbol, arg_params, aux_params)
  File "/usr/local/lib/python3.5/dist-packages/mxnet/model.py", line 197, in _multiple_callbacks
    cb(*args, **kwargs)
  File "/opt/sign2class/train_densenet_vdl.py", line 60, in _callback
    image0.add_sample(shape, list(data))
RuntimeError: [/work/VisualDL/visualdl/logic/sdk.cc:222]

**Comment by linshuliang** [comment]
image 组件并没有 add_sample() 这个成员函数。 
具体使用方法可参考
[visualdl 使用指南](https://paddlepaddle.org.cn/documentation/docs/zh/1.5/user_guides/howto/evaluation_and_debugging/debug/visualdl_usage.html#permalink-7-image-)

**Comment by IMJerryChen** [comment]
在demo/mxnet/mxnet_demo.py 这个文件里有image0.add_sample(shape, list(data))这个用法，大概在脚本的75行左右，如下这个函数里

def add_image_histogram():
    def _callback(iter_no, sym, arg, aux):
        image0.start_sampling()
        weight = arg['fullyconnected1_weight'].asnumpy()
        shape = [100, 50]
        data = weight.flatten()

        image0.add_sample(shape, list(data))
        histogram0.add_record(iter_no, list(data))

        image0.finish_sampling()

**Comment by linshuliang** [comment]
这个示例程序，可能是旧版本公布的 API，现在已经废弃了
