### ISSUE TITLE
可视化graph的时候报错KeyError: 'dim'

### ISSUE THREAD

**Issue by Michael3444** [PaddlePaddle/VisualDL#575]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/bin/visualdl", line 324, in graph
    json_str = vdl_graph.draw_onnx_graph(args.model_pb)
  File "/usr/local/lib/python2.7/dist-packages/visualdl/server/graph.py", line 491, in draw_onnx_graph
    json_str = load_model(model_pb_path)
  File "/usr/local/lib/python2.7/dist-packages/visualdl/server/graph.py", line 369, in load_model
    model_json = to_IR_json(model_pb_path)
  File "/usr/local/lib/python2.7/dist-packages/visualdl/server/graph.py", line 363, in to_IR_json
    reorganize_inout(model_json, 'input')
  File "/usr/local/lib/python2.7/dist-packages/visualdl/server/graph.py", line 51, in reorganize_inout
    shape = [dim['dimValue'] for dim in tensor_type['shape']['dim']]
KeyError: 'dim'

**Comment by ShenYuhan** [comment]
目前最新版的VisualDL(>=2.0.0b6)已经支持graph，比旧版更加方便易用，具体信息可以参照[graph](https://github.com/PaddlePaddle/VisualDL/blob/develop/docs/components/README.md#graph--%E7%BD%91%E7%BB%9C%E7%BB%93%E6%9E%84%E7%BB%84%E4%BB%B6)

建议使用新版VisualDL
