### ISSUE TITLE
vdl_create_scratch_log

### ISSUE THREAD

**Issue by linhandev** [PaddlePaddle/VisualDL#644]
目前 vdl_create_scratch_log 貌似已经无法正常执行，要下载的onnx链接已经失效。

`
vdl_create_scratch_log
[WARNING 2020-05-28 11:58:37,376 vdl_create_scratch_log:221] download ONNX file from https://github.com/PaddlePaddle/VisualDL/blob/develop/demo/mnist_model.onnx?raw=true
Traceback (most recent call last):
  File "/opt/conda/bin/vdl_create_scratch_log", line 228, in <module>
    download_onnx()
  File "/opt/conda/bin/vdl_create_scratch_log", line 222, in download_onnx
    onnx_model = ur.urlopen(onnx_url, context=myssl).read()
  File "/opt/conda/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/conda/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/conda/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/conda/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/conda/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/conda/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
`

**Comment by linhandev** [comment]
https://github.com/PaddlePaddle/VisualDL/blob/develop/demo/mnist_model.onnx?raw=true
![image](https://user-images.githubusercontent.com/29757093/83097806-95385380-a0db-11ea-8c5a-a10d4bd86d12.png)

**Comment by PeterPanZH** [comment]
VisualDL2.0已经废弃了这个脚本

**Comment by linhandev** [comment]
但是vdl2里他还是能执行，反正这个你们知道就好

**Comment by PeterPanZH** [comment]
谢谢反馈~
