### ISSUE TITLE
不能显示scalar数据

### ISSUE THREAD

**Issue by xiaomujiang** [PaddlePaddle/VisualDL#806]
环境：visualdl               2.0.0b7

参考 《VisualDL2.0--基于「手写数字识别」模型的全功能展示》 在aistudio 上 启动服务，可以显示文件，说明生产的文件没有问题，log文件名是paddle_lenet_log， 然后在**本地尝试，报错**： 
（1）启动服务
visualdl --logdir ./paddle_lenet_log --host 10.18.225.207  报一下错误：
[INFO 2020-09-09 18:14:32,975 app.py:141]  port=8040
Traceback (most recent call last):
  File "/root/anaconda3/envs/dog/bin/visualdl", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/dog/lib/python3.7/site-packages/visualdl/server/app.py", line 142, in main
    app = create_app(args)
  File "/root/anaconda3/envs/dog/lib/python3.7/site-packages/visualdl/server/app.py", line 55, in create_app
    api_call = create_api_call(args.logdir, args.model, args.cache_timeout)
  File "/root/anaconda3/envs/dog/lib/python3.7/site-packages/visualdl/server/api.py", line 161, in create_api_call
    api = Api(logdir, model, cache_timeout)
  File "/root/anaconda3/envs/dog/lib/python3.7/site-packages/visualdl/server/api.py", line 65, in __init__
    self._reader = LogReader(logdir)
  File "/root/anaconda3/envs/dog/lib/python3.7/site-packages/visualdl/reader/reader.py", line 62, in __init__
    self.load_new_data(update=True)
  File "/root/anaconda3/envs/dog/lib/python3.7/site-packages/visualdl/reader/reader.py", line 245, in load_new_data
    self.add_remain()
  File "/root/anaconda3/envs/dog/lib/python3.7/site-packages/visualdl/reader/reader.py", line 205, in add_remain
    component, dir, tag, record = self.parse_from_bin(item)
  File "/root/anaconda3/envs/dog/lib/python3.7/site-packages/visualdl/reader/reader.py", line 110, in parse_from_bin
    raise TypeError("Invalid value type `%s`." % value_type)
TypeError: Invalid value type `None`.
（2） visualdl --logdir ./paddle_lenet_log/lr0.001/vdlrecords.1599645887.log --host 10.18.225.207
这样可以启动服务，网络结构可以正常显示， 但是标量数据显示不了， 内容提示如下：

无可视化结果展示
有以下几种可能原因，请您参考相应解决方案：
未生成日志文件。请参考 README 创建日志文件。
已生成日志文件，但尚未打点数据。请参考 VisualDL使用指南 ，对需要进行可视化的数据进行打点记录。
已生成文件并打点数据，请尝试 刷新 。
已生成文件，但日志文件路径错误，请确保文件路径正确。

**Comment by xiaomujiang** [comment]
已经解决环境问题

**Comment by Ivancc99** [comment]
请问你是如何解决这个问题的呢？
