### ISSUE TITLE
记录训练过程中每一层网络权重（weight）、偏差（bias）的变化趋势时报错TypeError: find_var(): incompatible function arguments. The following argument types are supported:     1. (self: paddle.fluid.core_avx._Scope, name: str) -> paddle.fluid.core_avx.Variable

### ISSUE THREAD

**Issue by liu824** [PaddlePaddle/VisualDL#847]
W1113 14:13:06.573505 18627 device_context.cc:338] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 10.1
W1113 14:13:06.578078 18627 device_context.cc:346] device: 0, cuDNN Version: 7.6.
Loss at epoch 21 step 0: [3.3795364], acc: [0.0625]
Traceback (most recent call last):
  File "train.py", line 148, in <module>
    train(args)
  File "train.py", line 130, in train
    values = fluid.global_scope().find_var(param).get_tensor()
TypeError: find_var(): incompatible function arguments. The following argument types are supported:
    1. (self: paddle.fluid.core_avx._Scope, name: str) -> paddle.fluid.core_avx.Variable

Invoked with: <paddle.fluid.core_avx._Scope object at 0x7efc87d8b670>, Parameter containing:
Tensor(shape=[64, 3, 7, 7], dtype=float32, place=CUDAPlace(0), stop_gradient=False,
       [[[[-0.05371272,  0.02563002,  0.05632081, ..., -0.00026448, -0.00944346, -0.05984465],
          [-0.13191088, -0.06876908,  0.00257277, ..., -0.15187410,  0.08660244,  0.19309942],
          [-0.00409947,  0.20125084, -0.22973931, ...,  0.00727135,  0.15822206,  0.19260764],
          ...,
          [ 0.08105726, -0.09405645, -0.08971421, ...,  0.15416293, -0.12430244, -0.02890287],
          [-0.00469327, -0.13479811, -0.09286044, ..., -0.07483416, -0.00582452, -0.14144880],
          [ 0.03406075,  0.22536102,  0.11059787, ..., -0.04429235, -0.02568227,  0.17608106]],

         [[-0.20147945, -0.12044240, -0.01917759, ...,  0.10266569, -0.07594319,  0.17658979],
          [-0.15915743, -0.21526450,  0.17643879, ..., -0.09422915,  0.07671862,  0.06505689],
          [-0.00409845,  0.27419260, -0.12671664, ...,  0.07872657, -0.01545081, -0.04252915],
          ...,
          [ 0.08971966, -0.17341682, -0.06523058, ...,  0.03993573, -0.06482077, -0.13392194],
          [ 0.05021073, -0.10516340, -0.15193573, ...,  0.07946619, -0.08400706,  0.15694799],
          [-0.02634855,  0.06348091, -0.03298642, ..., -0.18717127, -0.20391597,  0.02536633]],

         [[ 0.03595769,  0.09444405, -0.11549302, ...,  0.09322303,  0.13165805, -0.04756674],
          [ 0.00502894,  0.13227703,  0.01322330, ...,  0.09432573, -0.06162579, -0.05716978],
          [-0.06110386,  0.21447718, -0.04460065, ...,  0.14836529,  0.22213607, -0.01830088],
          ...,
          [-0.16420029,  0.22314060, -0.13952385, ...,  0.17035939, -0.06986901, -0.15672506],
          [ 0.06202036, -0.15751627,  0.19456352, ...,  0.13588111, -0.08636770,  0.02866375],
          [ 0.22629906,  0.02967479,  0.08979870, ..., -0.10475618,  0.22713746, -0.00130036]]],

        [[[-0.16942094,  0.02158337, -0.02589060, ...,  0.17563400, -0.07153611, -0.02508573],
          [-0.09831343, -0.13857003,  0.02074831, ..., -0.05146887,  0.01467010,  0.09756473],
          [-0.06051393, -0.28088143, -0.21384186, ..., -0.01285089, -0.16261575, -0.00461356],
          ...,
          [-0.12890844,  0.01647253, -0.00549038, ..., -0.13342360,  0.17836629,  0.13808107],
          [-0.11562064, -0.17576179,  0.17740333, ..., -0.03589616, -0.14567600,  0.16230690],
          [ 0.14574505,  0.07636052, -0.01481463, ...,  0.09067488,  0.18608497,  0.00511809]],

         [[ 0.00683882, -0.17334856,  0.06513243, ..., -0.03233649, -0.09772876, -0.06745977],
          [ 0.01091705,  0.02337931,  0.06782591, ...,  0.18644181,  0.10856566, -0.17468967],
          [-0.15772916, -0.05068303, -0.16184428, ...,  0.03786005, -0.07222356, -0.01210173],
          ...,
          [-0.05068068, -0.00024234,  0.17443801, ..., -0.20538510, -0.05173780, -0.08395538],
          [ 0.35151914,  0.04523984,  0.00084386, ...,  0.26847491, -0.06740268,  0.04466518],
          [-0.12147009,  0.06833526, -0.01292913, ...,  0.17552084,  0.08977843,  0.08533600]],

         [[ 0.13397469, -0.08877946,  0.09465269, ..., -0.01420754, -0.07884943, -0.09773644],
          [-0.03883518,  0.08648926,  0.06258298, ...,  0.03134510, -0.08580495, -0.07691327],
          [ 0.12963583,  0.25313574, -0.21642633, ..., -0.04318970,  0.02013852, -0.12151419],
          ...,
          [-0.13584189,  0.06477021, -0.04785471, ..., -0.13979413,  0.04039805,  0.09097884],
          [ 0.01519525, -0.04246537, -0.07933698, ...,  0.04873319,  0.09172934,  0.05996808],
          [-0.15594552,  0.05536261,  0.02160008, ..., -0.18382011, -0.12463959, -0.27031586]]],

        [[[-0.18956815, -0.11202557, -0.06647276, ...,  0.10624201,  0.07278875, -0.00757997],
          [ 0.06851072,  0.10664992,  0.05387084, ..., -0.06821573,  0.07183297,  0.16260338],
          [-0.03678593,  0.04537305, -0.04535407, ...,  0.14237596, -0.23168732,  0.01414812],
          ...,
          [-0.06027520, -0.14664808, -0.20756459, ...,  0.24425733,  0.21042559,  0.14230514],
          [-0.05899965, -0.08804140, -0.12899646, ..., -0.01688674, -0.04454982,  0.19649015],
          [ 0.23456690,  0.02187125,  0.12533526, ..., -0.04732814, -0.13458855, -0.10670327]],

         [[-0.11765036,  0.14602011, -0.00394781, ...,  0.26919621, -0.11819906,  0.11808609],
          [ 0.07208485,  0.15819131,  0.23001160, ...,  0.03093377,  0.17098770, -0.13327394],
          [-0.01058664,  0.24288347, -0.15801650, ...,  0.25152615,  0.01163305,  0.02783292],
          ...,
          [-0.04268812,  0.02718713, -0.21264891, ..., -0.01309919,  0.02145981, -0.15937288],
          [-0.00091560, -0.09590320,  0.02676556, ..., -0.06401808,  0.11553966, -0.12741746],
          [ 0.05555905,  0.12809832,  0.04530699, ...,  0.20844726, -0.05680595, -0.16282511]],

         [[ 0.03593145, -0.01238057, -0.28665593, ...,  0.11611426,  0.08043572, -0.04284764],
          [ 0.17479017,  0.16913784,  0.03981280, ..., -0.10573972, -0.09940572,  0.06275295],
          [-0.07737350,  0.00348559,  0.09646266, ...,  0.12809682, -0.02139325,  0.07446396],
          ...,
          [ 0.11253589,  0.00914980, -0.01889215, ..., -0.16781101,  0.07759926,  0.08914097],
          [ 0.03129834, -0.14662820,  0.17885587, ...,  0.07079007, -0.18597242, -0.13504593],
          [ 0.08918712, -0.08912317,  0.10162397, ...,  0.26869425, -0.20693648,  0.16643156]]],

        ...,

        [[[-0.10666604, -0.04953630,  0.10014477, ..., -0.23619394, -0.09643595,  0.07345195],
          [ 0.03212913,  0.12063932, -0.08243246, ...,  0.05631124, -0.01953767, -0.03619465],
          [-0.12486877, -0.03365948,  0.05842570, ..., -0.12869607, -0.08509632, -0.09662653],
          ...,
          [-0.02235440, -0.00376477,  0.03449876, ...,  0.22438061, -0.04179811,  0.01268044],
          [-0.04384780,  0.00758245, -0.20417081, ...,  0.00634575,  0.02732186,  0.00151208],
          [ 0.05696646, -0.10150784, -0.04583076, ..., -0.00244777, -0.03226490, -0.10297437]],

         [[ 0.02085448,  0.08298834,  0.01194736, ...,  0.17886707, -0.04070437, -0.14953811],
          [-0.09593403, -0.04079718, -0.23361385, ...,  0.00398310,  0.18993473, -0.00488889],
          [-0.15352899, -0.30027050, -0.03512340, ..., -0.00949531, -0.02089255, -0.03371822],
          ...,
          [-0.04266144,  0.06187467,  0.06956232, ..., -0.25062302, -0.08702695,  0.18046835],
          [-0.07674308,  0.04229528, -0.07133981, ..., -0.04639657, -0.12081505,  0.23334664],
          [ 0.06449755, -0.02589688, -0.03544202, ...,  0.11364019,  0.04153372, -0.05607167]],

         [[ 0.01986482, -0.01588563, -0.07213204, ...,  0.05885765,  0.03186589,  0.19851105],
          [ 0.08522888, -0.08616970, -0.02668670, ...,  0.06151600,  0.00666960,  0.16714014],
          [ 0.08271327, -0.05358266,  0.02598779, ..., -0.09574778, -0.15135407, -0.17411508],
          ...,
          [-0.02997489, -0.03402816,  0.02100774, ...,  0.13545223, -0.12205386,  0.20063105],
          [-0.01682661, -0.02726187, -0.02448392, ..., -0.10504176, -0.14989460,  0.11606291],
          [-0.05824291, -0.05442714,  0.00415404, ...,  0.17161493, -0.01001993,  0.07579793]]],

        [[[-0.11983357, -0.24511543,  0.02383022, ...,  0.00949601,  0.04676761,  0.02172404],
          [-0.00676098,  0.04665466,  0.02605842, ..., -0.11257137,  0.13505463, -0.06166860],
          [-0.08642399, -0.00440849,  0.04427905, ...,  0.08311862, -0.02560344, -0.00700521],
          ...,
          [-0.31220728, -0.04690372,  0.02224578, ...,  0.08773822,  0.03001952, -0.07991468],
          [-0.01925143,  0.03457034,  0.02701436, ...,  0.08252417,  0.15190767,  0.12629896],
          [-0.22712429,  0.09026576,  0.16203041, ..., -0.05994258,  0.13855256,  0.02488234]],

         [[ 0.15267454,  0.01927627,  0.07595592, ..., -0.20298408,  0.19097120,  0.05016575],
          [ 0.22450916,  0.17005849, -0.09621581, ..., -0.20312390,  0.11807272,  0.12250015],
          [ 0.03116199, -0.05957430, -0.01876112, ...,  0.03168613,  0.08469277,  0.01135335],
          ...,
          [ 0.12374663, -0.11256499, -0.02217926, ..., -0.05647057, -0.09042959,  0.11440323],
          [-0.02911502, -0.01316030, -0.21584439, ...,  0.19504678, -0.08425514, -0.04984520],
          [ 0.04201146,  0.26155245, -0.10509497, ..., -0.08584149,  0.08095059,  0.00928190]],

         [[-0.12199288, -0.11594301, -0.06125667, ...,  0.01283419, -0.11479117, -0.08256131],
          [-0.10273959, -0.18086842,  0.16882572, ...,  0.03532395,  0.01470157,  0.07667703],
          [-0.03524869, -0.11353942, -0.15292215, ...,  0.00566387,  0.05137567,  0.06996670],
          ...,
          [-0.09765739,  0.04625426, -0.00743870, ..., -0.02850227, -0.11995047, -0.04550475],
          [-0.00108890,  0.04460265,  0.15640296, ..., -0.04094482, -0.08771304,  0.12531202],
          [-0.08961136, -0.01154350, -0.00974052, ...,  0.08636782,  0.13973930, -0.02640737]]],

        [[[-0.00647218,  0.01204356, -0.13710225, ...,  0.14272004,  0.07551459,  0.10770768],
          [-0.05599879, -0.10912941, -0.01907041, ..., -0.08270092, -0.06221725,  0.00915189],
          [-0.07690013, -0.00442671, -0.03614078, ..., -0.00326806,  0.24360371,  0.17214419],
          ...,
          [ 0.02649835, -0.19732317, -0.15525614, ...,  0.05480768,  0.01460017, -0.09393326],
          [ 0.04479250, -0.06939436, -0.11037678, ..., -0.07796583, -0.05275495, -0.04132050],
          [-0.00665381, -0.00354639, -0.02932873, ..., -0.22171618,  0.03693261,  0.14127247]],

         [[ 0.05373741,  0.02270398,  0.24679226, ..., -0.14266175,  0.01733061,  0.01913098],
          [-0.13761315, -0.08920770, -0.07965924, ..., -0.00690528,  0.02210638,  0.09430081],
          [ 0.12819508, -0.19130833,  0.11555462, ..., -0.18031920,  0.20774245,  0.07101668],
          ...,
          [ 0.01804224,  0.14461114,  0.07339010, ..., -0.24618986, -0.12672570,  0.07960801],
          [ 0.20152439,  0.00318818,  0.11003289, ..., -0.01770172, -0.27444020, -0.08470830],
          [ 0.00809342,  0.18264174, -0.05213420, ..., -0.15177633, -0.03352364,  0.07203823]],

         [[ 0.01053809,  0.03918225,  0.02575882, ..., -0.08716466, -0.17550117, -0.12532315],
          [ 0.16672143,  0.13479738, -0.06526640, ..., -0.09899871,  0.17399231,  0.21997011],
          [ 0.00337980,  0.16451176,  0.03519333, ...,  0.21176545, -0.01850528,  0.07370484],
          ...,
          [-0.16110294, -0.16706827, -0.01364933, ...,  0.03146618, -0.01525439,  0.17832349],
          [-0.16439562,  0.05771317, -0.12991007, ...,  0.16630079, -0.19178662, -0.24534179],
          [ 0.10021880,  0.01017394, -0.15857616, ..., -0.26201367,  0.23844700,  0.04679514]]]])

**Comment by liu824** [comment]
wo我发现哪错了，这里需要的是param.name,而不是param
