### ISSUE TITLE
启动训练，VDL报错

### ISSUE THREAD

**Issue by rock4you** [PaddlePaddle/VisualDL#862]
python pdseg/train.py --cfg configs/unet_optic.yaml \
                      --use_gpu \
                      --do_eval \
                      --use_vdl \
                      --vdl_log_dir train_log \
                      BATCH_SIZE 4 \
                      SOLVER.LR 0.001
报错：
Traceback (most recent call last):                                                                              
  File "pdseg/train.py", line 468, in <module>                                                                  
    main(args)                                                                                                  
  File "pdseg/train.py", line 454, in main                                                                      
    train(cfg)                                                                                                  
  File "pdseg/train.py", line 298, in train                                                                     
    log_writer = LogWriter(args.vdl_log_dir)                                                                    
TypeError: __init__() takes at least 3 arguments (2 given)

**Comment by rock4you** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/user_guides/howto/evaluation_and_debugging/debug/visualdl.html
需要注意，官方自2020年1月1日起不再维护Python2，为了保障代码可用性，VisualDL现仅支持Python3
使用python3即可
