### ISSUE TITLE
python setup.py bdist_wheel 时报错

### ISSUE THREAD

**Issue by Liudyan** [PaddlePaddle/VisualDL#991]
按照官方只能装教程，执行
python setup.py bdist_wheel时
出现
(base) C:\Users\liudy\VisualDL>python setup.py bdist_wheel
Traceback (most recent call last):
  File "setup.py", line 42, in <module>
    README = read('README.md')
  File "setup.py", line 35, in read
    return open(os.path.join(TOP_DIR, name)).read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 5: illegal multibyte sequence
错误。

**Comment by PeterPanZH** [comment]
暂时不支持windows系统下编译，请通过pip安装，谢谢
